<?php

namespace OC\PrepBundle\Repository;

/**
 * PictureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PictureRepository extends \Doctrine\ORM\EntityRepository
{
    public function findIdToJoin()
    {
        $em = $this->getEntityManager();
        $qb= $em->createQueryBuilder();

        $qb->select(array('p','t'))
            ->from('OCPrepBundle:Picture', 'p')
            ->join('p.trick','t');

         $result=$qb->getQuery()->getResult();

        try{

            return $result;

        }catch (\Doctrine\ORM\NoResultException $e){

            return null;
        }
    }
}
