<?php

namespace OC\PrepBundle\Repository;

/**
 * TricksCreationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TricksCreationRepository extends \Doctrine\ORM\EntityRepository
{
}
