<?php

namespace OC\PrepBundle\Repository;
/**
 * TrickRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrickRepository extends \Doctrine\ORM\EntityRepository
{
    public function findTrick($id)
    {
        $em = $this->getEntityManager()->createQueryBuilder();

        $qb = $em->select('t')
                 ->from('OCPrepBundle:Trick', 't')
                 ->where('t.id = :id')
                 ->setParameter('id',$id);

        $result = $qb->getQuery()->getResult();

        try{

            return $result;

        }catch (\Doctrine\ORM\NoResultException $e){

            return null;
        }
    }

    public function findTrickAndPics($id)
    {
        $em = $this->getEntityManager()->createQueryBuilder();
        $qb = $em->select(array('t','p'))
            ->from('OCPrepBundle:Picture', 'p')
            ->join('p.trick', 't')
            ->where('t.id = :id')
            ->andWhere('p.trick = t.id')
            ->setParameter('id',$id);

        $result = $qb->getQuery()->getResult();

        try{

            return $result;

        }catch (\Doctrine\ORM\NoResultException $e){

            return null;
        }
    }

    public function findTrickAndVideo($id)
    {
        $em = $this->getEntityManager()->createQueryBuilder();
        $qb = $em->select(array('t','v'))
            ->from('OCPrepBundle:Video', 'v')
            ->join('v.trick', 't')
            ->where('t.id = :id')
            ->andWhere('v.trick = t.id')
            ->setParameter('id',$id);

        $result = $qb->getQuery()->getResult();

        try{

            return $result;

        }catch (\Doctrine\ORM\NoResultException $e){

            return null;
        }
    }

}
