<?php

namespace OC\PrepBundle\Repository;

/**
 * TricksGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TricksGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
