<?php

namespace OC\PrepBundle\Repository;

/**
 * UserCredRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserCredRepository extends \Doctrine\ORM\EntityRepository
{
}
